;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cider-refresh
        evil-append-line
        evil-backward-WORD-begin
        evil-backward-char
        evil-backward-word-begin
        evil-delete-char
        evil-delete-line
        evil-digit-argument-or-evil-beginning-of-line
        evil-emacs-state
        evil-end-of-line
        evil-exit-visual-state
        evil-force-normal-state
        evil-forward-WORD-begin
        evil-forward-WORD-end
        evil-forward-char
        evil-forward-word-begin
        evil-forward-word-end
        evil-insert
        evil-next-line
        evil-normal-state
        evil-previous-line
        ))

(setq mc/cmds-to-run-once
      '(
        evil-inner-tag
        evil-mouse-drag-region
        evil-search-next
        save-buffers-kill-terminal
        sp-backward-delete-char
        ))
